#+TITLE: org-reminders

org-reminders 是一个 Emacs 插件，旨在促进 macOS Reminders（提醒事项）和 Org mode 之间的交互。该插件允许您在 Org mode 中管理存储在 macOS Reminders 中的提醒事项，为依赖这两个系统的用户提供无缝体验。

该项目进行了大规模的重构，旧版本保留在 [[https://github.com/ginqi7/org-reminders/tree/v1][v1]] 分支中。

* 功能
- 自动同步：当 Org Mode 文件发生更改并保存，或提醒事项有更新时，系统会自动完成同步，确保两端数据实时一致。
- 无缝映射：它能够将 Org Mode 的 Todo 功能与提醒事项的核心概念进行智能映射，实现两者之间的流畅转换与兼容。

https://github.com/user-attachments/assets/f6487deb-d1e4-4d03-ba03-57a0409ac596

* 详解视频
https://www.bilibili.com/video/BV1tiX5YFEZZ/

* 前提条件
[[https://github.com/ginqi7/org-reminders-cli][org-reminders-cli]] : 一个用于将 macOS 提醒事项与 Emacs Org Mode 同步的命令行工具，专为与 ginqi7/org-reminders 配合使用而设计。

** Emacs 依赖项   

- [[https://github.com/ginqi7/websocket-bridge][websocket-bridge]] : 一个通过WebSocket连接Emacs和Swift程序的桥接工具。
- [[https://github.com/ahyatt/emacs-websocket][emacs-websocket]] : 一个用elisp实现的WebSocket库，供Emacs使用。

* 安装
** reminders-cli
#+begin_src shell
brew install ginqi7/formulae/org-reminders-cli
#+end_src

** 授予提醒事项访问权限
当您遇到错误：
#+begin_quote
"error: you need to grant reminders access\n"
#+end_quote
在 Eshell 中运行以下命令将填充 Emacs 的权限。
#+begin_src shell
osascript -e 'tell application "Reminders" to show (first list whose name is "blabla")'
#+end_src

** 安装包

- 将项目克隆到您自己的 Emacs 配置文件目录中，例如：
#+begin_src shell
  git clone git@github.com:ginqi7/org-reminders.git ~/.emacs.d/lisp/org-reminders
  git clone git@github.com:ginqi7/websocket-bridge.git ~/.emacs.d/lisp/websocket-bridge
  git clone git@github.com:ahyatt/emacs-websocket.git ~/.emacs.d/lisp/emacs-websocket
#+end_src

- 将路径添加到 ‘load-path’：
#+begin_src emacs-lisp
  (add-to-list 'load-path (expand-file-name "~/.emacs.d/lisp/websocket-bridge"))
  (add-to-list 'load-path (expand-file-name "~/.emacs.d/lisp/emacs-websocket"))
  (add-to-list 'load-path (expand-file-name "~/.emacs.d/lisp/org-reminders"))
#+end_src

* 配置
将以下行添加到您的 Emacs 配置文件（例如，.emacs 或 init.el）：
#+begin_src emacs-lisp
(require 'org-reminders)
#+end_src

* 变量
| 变量                          | 描述                                                                                      | 默认值                     |
|-------------------------------+-------------------------------------------------------------------------------------------+----------------------------|
| org-reminders-sync-file       | 指定将数据同步到哪个 Org Mode 文件。                                                         | "~/.emacs.d/Reminders.org" |
| org-reminders-display-options | 显示提醒事项的内容，默认显示全部。可选值为：all（全部）、incomplete（未完成）或 complete（已完成）。 | "all"                      |
| org-reminders-sync-frequency  | 同步频率，表示保存文件多少次触发一次同步，默认值为 1。                                           | 1                          |


* 用法
** A Transient Prefix
- *org-reminders-prefix* : 定义了一个 transient-prefix，可以快速的访问多个 org-reminders 命令
** org-reminders-sync-all
将所有提醒事项数据刷新为 Org 格式。
** org-reminders-restart-auto-sync
启用 Org Mode 文件与提醒事项之间的自动同步功能。

** 查看日志
- 运行 =websocket-bridge-app-log-buffer= 选择 =org-reminders=


* 贡献
欢迎贡献！请通过项目的存储库提交问题和拉取请求。
