#+TITLE: org-reminders

#+HTML: <a href ="https://github.com/ginqi7/org-reminders/blob/master/README.zh-CN.org"><img src="https://img.shields.io/badge/README-%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87-555555.svg"/></a>

org-reminders is an Emacs plugin designed to facilitate interactions between macOS Reminders and Org mode. The plugin allows you to manage reminders stored in macOS Reminders from within Org mode, providing a seamless experience for users who rely on both systems.

The project underwent a large-scale refactoring, with the old version maintained in the [[https://github.com/ginqi7/org-reminders/tree/v1][v1]] ranch.

* Features

- *Automatic synchronization* : Org Mode files and reminders sync automatically upon saving or updates, ensuring real-time data consistency across devices.
- *Seamlessly mapping* : Org Mode's Todo functionality to Reminders' core concepts for fluid conversion and compatibility.

https://github.com/user-attachments/assets/f6487deb-d1e4-4d03-ba03-57a0409ac596

* Detailed Video
https://youtu.be/RrR4EXZgYmU

* Prerequisites

- *[[https://github.com/ginqi7/org-reminders-cli][org-reminders-cli]]* : A CLI tool for syncing OS X Reminders with Emacs org-mode, designed to work with ginqi7/org-reminders.

** Emacs dependencies
- [[https://github.com/ginqi7/websocket-bridge][websocket-bridge]] : A bridge that connects Emacs and Swift programs via WebSocket.
- [[https://github.com/ahyatt/emacs-websocket][emacs-websocket]] : A websocket implementation in elisp, for emacs.

* Installation

** reminders-cli
#+begin_src shell
brew install ginqi7/formulae/org-reminders-cli
#+end_src

* grant reminders access
When you encounter an error :

#+begin_quote
"error: you need to grant reminders access\n"
#+end_quote

Running this command in Eshell will populate Emacs permissions.
#+begin_src shell
  osascript -e 'tell application "Reminders" to show (first list whose name is "blabla")'
#+end_src

** package

- clone the project in your own emacs configuration files directory, like:
#+begin_src shell
  git clone git@github.com:ginqi7/org-reminders.git ~/.emacs.d/lisp/org-reminders
  git clone git@github.com:ginqi7/websocket-bridge.git ~/.emacs.d/lisp/websocket-bridge
  git clone git@github.com:ahyatt/emacs-websocket.git ~/.emacs.d/lisp/emacs-websocket
#+end_src

The [[https://elpa.gnu.org/packages/websocket.html][emacs-websocket]] can be downloaded from ELPA.

- add the path to ‘load-path’
#+begin_src emacs-lisp
  (add-to-list 'load-path (expand-file-name "~/.emacs.d/lisp/websocket-bridge"))
  (add-to-list 'load-path (expand-file-name "~/.emacs.d/lisp/emacs-websocket"))
  (add-to-list 'load-path (expand-file-name "~/.emacs.d/lisp/org-reminders"))
#+end_src

* Configuration
Add the following line to your Emacs configuration file (e.g., `.emacs` or `init.el`):

#+begin_src emacs-lisp
  (require 'org-reminders)
#+end_src

* Variables
| variable                      | description                                                                                                                  | default-value              |
|-------------------------------+------------------------------------------------------------------------------------------------------------------------------+----------------------------|
| org-reminders-sync-file       | Specify which Org Mode file to synchronize the data to.                                                                      | "~/.emacs.d/Reminders.org" |
| org-reminders-display-options | Display the content of those reminders, with the default being all. The available options are: all, incomplete, or complete. | "all"                      |
| org-reminders-sync-frequency  | The synchronization frequency, indicating how many file saves trigger one synchronization, is set to 1 by default.           | 1                          |


* Usage
** A Transient Prefix
- *org-reminders-prefix* : A transient prefix for multiple org-reminders commands.
** org-reminders-sync-all
Flush all Reminders data to Org manner
** org-reminders-restart-auto-sync
Enable automatic synchronization between Org Mode files and Reminders.
** Check Log
- run =websocket-bridge-app-log-buffer= select =org-reminders=

* Contributions
Contributions are welcome! Please submit issues and pull requests through the project’s repository.
